-- AlterTable
ALTER TABLE `Employe` ADD COLUMN `role` ENUM('USER', 'EMPLOYE') NOT NULL DEFAULT 'EMPLOYE';

-- AlterTable
ALTER TABLE `User` ADD COLUMN `role` ENUM('USER', 'EMPLOYE') NOT NULL DEFAULT 'USER';
